server:
  port: 8020

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

mybatis-plus:
  # 扫描mapper.xml文件
  mapper-locations: classpath:/mappers/*Mapper.xml
  # 扫描实体类,多个package用逗号或者分号分隔
  typeAliasesPackage: me.mrniurh.mybatisplustest.entity
  # 主键类型
  global-config:
    #关闭MP3.0自带的banner
    banner: false
    db-config:
      #0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 0
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  #自定义SQL注入器
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl